# Copyright 2018-2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.2"

[buildpack]
id      = "paketo-buildpacks/eclipse-openj9"
name    = "Paketo Eclipse OpenJ9 Buildpack"
version = "{{.Version}}"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata.default-versions]
jdk = "11.*"
jre = "11.*"

[[metadata.dependencies]]
id      = "jre"
name    = "OpenJ9 JRE"
version = "8.0.242"
uri     = "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08_openj9-0.18.1/OpenJDK8U-jre_x64_linux_openj9_8u242b08_openj9-0.18.1.tar.gz"
sha256  = "985d3134b64c6196d4c9ddbc87af0c62b0e643cef71b29f3d25a8c7811811745"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
  uri  = "https://github.com/eclipse/openj9/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "jre"
name    = "OpenJ9 JRE"
version = "11.0.6"
uri     = "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10_openj9-0.18.0/OpenJDK11U-jre_x64_linux_openj9_11.0.6_10_openj9-0.18.0.tar.gz"
sha256  = "273e9f6a17a27c713407883898bd137f0a4ee1b8a0a4b42a1f7ec22225e01166"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
  uri  = "https://github.com/eclipse/openj9/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "jre"
name    = "OpenJ9 JRE"
version = "14"
uri     = "placeholder"
sha256  = "placeholder"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
  uri  = "https://github.com/eclipse/openj9/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "jdk"
name    = "OpenJ9 JDK"
version = "8.0.242"
uri     = "https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u242-b08_openj9-0.18.1/OpenJDK8U-jdk_x64_linux_openj9_8u242b08_openj9-0.18.1.tar.gz"
sha256  = "ca785af638b24f9d4df896f5a9f557cc9f1e5fa5e2b1174d6b906e3fd5474c2e"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
  uri  = "https://github.com/eclipse/openj9/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "jdk"
name    = "OpenJ9 JDK"
version = "11.0.6"
uri     = "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.6%2B10_openj9-0.18.0/OpenJDK11U-jdk_x64_linux_openj9_11.0.6_10_openj9-0.18.0.tar.gz"
sha256  = "e9b36d476dc9da8797bad6497e96f30c85ff6880e930a2ab31e34fbba87d0498"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
  uri  = "https://github.com/eclipse/openj9/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "jdk"
name    = "OpenJ9 JDK"
version = "14"
uri     = "placeholder"
sha256  = "placeholder"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception"
  uri  = "https://github.com/eclipse/openj9/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "jvmkill"
name    = "JVMKill Agent"
version = "1.16.0"
uri     = "https://java-buildpack.cloudfoundry.org/jvmkill/bionic/x86_64/jvmkill-1.16.0-RELEASE.so"
sha256  = "a3092627b082cb3cdbbe4b255d35687126aa604e6b613dcda33be9f7e1277162"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/jvmkill/blob/master/LICENSE"

[[metadata.dependencies]]
id      = "memory-calculator"
name    = "Memory Calculator"
version = "4.0.0"
uri     = "https://java-buildpack.cloudfoundry.org/memory-calculator/bionic/x86_64/memory-calculator-4.0.0.tgz"
sha256  = "90d40eab6959a7b4059c6409c4505040e8a04f75a481f7282e53430df3edda3e"
stacks  = [ "io.buildpacks.stacks.bionic" ]

  [[metadata.dependencies.licenses]]
  type = "Apache-2.0"
  uri  = "https://github.com/cloudfoundry/java-buildpack-memory-calculator/blob/master/LICENSE"

[metadata]
pre-package   = "scripts/build.sh"
include-files = [
  "LICENSE",
  "NOTICE",
  "README.md",
  "bin/build",
  "bin/class-counter",
  "bin/detect",
  "bin/link-local-dns",
  "bin/security-providers-configurer",
  "buildpack.toml",
]
